name: selfservicekiosk
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rflutter_alert:
    git: git://github.com/RatelHub/rflutter_alert.git
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  firebase_core: ^0.4.0+8
  http: ^0.12.0+2



  cloud_firestore: ^0.12.9


  firebase_auth: ^0.14.0
  redux: ^3.0.0
  flutter_redux: ^0.5.1
  url_launcher: ^5.1.1
  google_sign_in: ^3.2.2
  flutter_redux_dev_tools: ^0.3.0
  redux_dev_tools: ^0.4.0
  firebase_messaging: ^5.1.2
  sqflite: ^1.1.1

  shared_preferences: ^0.5.3

  flutter_bloc: ^0.15.0
  countdown: ^0.1.0
  equatable: ^0.2.0
  wave: ^0.0.8

  flutter_map: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
  - family: Nunito
    fonts:
       #- assets: assets/Nunito-Regular.ttf
       #- assets: assets/Nunito-Light.ttf
    - asset: assets/Nunito-Bold.ttf
       #- assets: assets/Nunito-Regular.ttf
       #- assets: assets/Nunito-Regular.ttf
       #- assets: assets/Nunito-Regular.ttf
       #- assets: assets/Nunito-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/PNGFile/Self Service Kiosk_Cancel order.png
    - images/PNGFile/Self Service Kiosk_Card.png
    - images/PNGFile/Self Service Kiosk_Dine in- Take Away.png
    - images/PNGFile/Self Service Kiosk_Gojek.png
    - images/PNGFile/Self Service Kiosk_Link Aja.png
    - images/PNGFile/Self Service Kiosk_Order.png
    - images/PNGFile/Self Service Kiosk_OVO scanner.png
    - images/PNGFile/Self Service Kiosk_Ovo.png
    - images/PNGFile/Self Service Kiosk_Receipt.png
    - images/PNGFile/Self Service Kiosk_Select Hot Cold _ Size.png
    - images/PNGFile/Self Service Kiosk_Select Payment Method copy.png
    - images/PNGFile/Self Service Kiosk_Select Payment Method.png
    - images/PNGFile/Self Service Kiosk_Select Sugar _ Ice.png
    - images/PNGFile/Self Service Kiosk_Shopping Cart.png
    - images/PNGFile/Self_Service_Kiosk_Start_Screen.png
    - images/PNGFile/background.png
    - images/PNGFile/overeazy_white.png
    - images/PNGFile/banner.png
    - images/PNGFile/menu_5.png
    - images/PNGFile/menu 1.png
    - images/PNGFile/menu 6.png
    - images/PNGFile/menu 2.png
    - images/PNGFile/menu 3.png
    - images/PNGFile/menu 4.png
    - images/PNGFile/banner_withtext.png
    - images/icons/home.png
    - images/icons/home_border.png
    - images/PNGFile/tab bar_review order.png
    - images/PNGFile/tab bar_overeazy.png
    - images/icons/warning.png
    - images/icons/payment_ewallet.png
    - images/icons/ewallet_gopay.png
    - images/icons/ewallet_linkaja.png
    - images/icons/ewallet_ovo.png
    - images/icons/take_away.png
    - images/icons/dine_in.png
    - images/icons/pay_scanovo.png
    - images/icons/payment_card.png
    - images/icons/qr_gopay.png
    - images/icons/qr_linkaja.png
    - images/icons/qr_ovo.png
    - images/icons/pay_card.png
    - images/icons/cold_large.png
    - images/icons/cold_medium.png
    - images/icons/cold_small.png
    - images/icons/hot_small.png
    - images/icons/hot_medium.png
    - images/icons/hot_large.png
    - images/icons/payment1.png
    - images/icons/payment2.png
    - images/icons/ice_no.png
    - images/icons/ice_normal.png
    - images/icons/ice_less.png
    - images/icons/ice_more.png
    - images/icons/sugar_no.png
    - images/icons/sugar_normal.png
    - images/icons/sugar_less.png
    - images/icons/sugar_more.png
    - images/icons/receipt.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
